#! /usr/bin/env perl

use strict;
use warnings;

use Config::Scoped;
use File::HomeDir;
use Getopt::Long;
use Data::SimplePassword;
use DateTime::TimeZone;
use WWW::LiveChat::API;

# process commandline parameters
my %opts = (id => '', name => '', 'display-name' => '',
	    email => '', login => '', password => '');

my $whandler = $SIG{__WARN__};
$SIG{__WARN__} = sub {print STDERR "$0: @_";};
unless (GetOptions (\%opts, 'chatting', 'debug', 'delete', 'id=s', 
		    'name=s', 'display-name=s',
		    'email=s', 'operator=i', 'timezone=s',
		    'login=s', 'password=s')) {
	exit 1;
}
$SIG{__WARN__} = $whandler;

$opts{display_name} = delete $opts{'display-name'};

my $function;

if (@ARGV) {
    $function = shift;
}
else {
    $function = 'operators';
}

my $tz = DateTime::TimeZone->new(name => 'local');

# determine location of configuration file
my ($conffile, $confparser, $confref, @errors);

$conffile = join('/', File::HomeDir->my_home, '.livechatrc');

# parse configuration file

$confparser = Config::Scoped->new(file => $conffile);

$confref = $confparser->parse->{_GLOBAL};

for (qw/login api_key/) {
    unless (exists $confref->{$_} && $confref->{$_} =~ /\S/) {
	push @errors, "Missing value for $_ in configuration file.";
    }
}

if (@errors) {
    for (@errors) {
	warn $_, "\n";
    }
    exit 1;
}

my $lcapi = WWW::LiveChat::API->new(login => $confref->{login},
				    api_key => $confref->{api_key},
				    timezone => $tz->name,
				    debug => $opts{debug},
);

my (%data, $ops);

if ($opts{login} && ! $opts{id}) {
	# check whether record exists already
	$ops = $lcapi->_build_function($function);

	if (ref($ops) eq 'ARRAY') {
		for my $ref (@$ops) {
			if ($ref->{login} eq $opts{login}) {
				$opts{id} = $ref->{id};
			}
		}
	}
}

for my $var (qw/name display_name email login password operator timezone/) {
	if ($opts{$var}) {
		$data{$var} = $opts{$var};
	}
}

if ($opts{delete}) {
    $ops = $lcapi->dispatch(function => $function, 
			    id => $opts{id},
			    data => undef,
	);
}
elsif (keys %data) {
    my @params = (function => $function);

    if ($opts{id}) {
	push (@params, $opts{id});
    }

    if ($function eq 'operators'
	&& ! $opts{id} && ! $opts{password}) {
	my ($pw, $pwgen);

	$pwgen = Data::SimplePassword->new();
	$pwgen->make_password(8);
	$data{password} = $pw;
    }
	
    $ops = $lcapi->dispatch(@params, data => \%data);
}
else {
    $ops = $lcapi->dispatch(function => $function, 
			    id => $opts{id},
			    chatting => $opts{chatting},
	);
}

use Data::Dumper;
print Dumper($ops);

									
